application: colbyskeggs
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: latest
- name: pycrypto
  version: "2.6"

handlers:
- url: /images
  static_dir: images
- url: /.*
  script: main.application
  secure: never
